footprint: [[-0.1, -0.15], [-0.1, 0.15], [0.1, 0.15], [0.10, -0.15]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0


observation_sources: laser
laser: {data_type: LaserScan, clearing: true, marking: true, topic: /diff_bot/laser/scan, inf_is_valid: true}


#robot_radius: ir_of_robot
inflation_radius: 0.25